{{- $hasInline := false -}}
{{- range .Values.app.configs -}}
  {{- if and . (eq .source "inline") -}}
    {{- $hasInline = true -}}
  {{- end -}}
{{- end -}}

{{- if $hasInline }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynamic-form.fullname" . }}-inline-configs
  labels:
    {{- include "dynamic-form.labels" . | nindent 4 }}
data:
  {{- range .Values.app.configs }}
  {{- if and . .id (eq .source "inline") }}
  {{ .id }}.yaml: |
    {{- .inline.schema | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
