{{- range .Values.app.configs }}
{{- if and . .id (eq .source "git") .git .git.token (not .git.existingTokenSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "formatter.fullname" $ }}-git-token-{{ .id }}
  labels:
    {{- include "formatter.labels" $ | nindent 4 }}
type: Opaque
data:
  GIT_TOKEN: {{ .git.token | b64enc | quote }}
{{- end }}
{{- end }}
