{{- if and (eq .Values.config.source "git") .Values.config.git.token (not .Values.config.git.existingTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamic-form.fullname" . }}-git-token
  labels:
    {{- include "dynamic-form.labels" . | nindent 4 }}
type: Opaque
data:
  GIT_TOKEN: {{ .Values.config.git.token | b64enc | quote }}
{{- end }}
